stages:
  - test
  - dist
  - deploy

Dist:
  stage: dist
  script:
    - make dist
  tags:
    - linux
  only:
    - master

Test:
  stage: test
  script:
    - make test
  tags:
    - linux
  except:
    - tags

Deploy:
  stage: deploy
  script:
    - make deploy
  tags:
    - linux
  only:
    - master

Sonar Scan:
  stage: scan
  script:
    - make scan
  tags:
    - linux
  only:
    - master
